### ISSUE TITLE
[v2] Protocol Updates

### ISSUE THREAD

**Issue by wessupermare** [ivao-xa/TrainingServer#20]
# Goal 
v2 will feature a real-time protocol with lag compensation.

# Sub-tasks
- [x] Develop new protocol.
- [ ] Create web hub.
- [ ] Add protocol support to [Borealis](https://github.com/wessupermare/Borealis).
- [ ] Rewrite server based on new protocol.
